### PR TITLE
Some code cleaning

### PR DESCRIPTION
**Pull request by nalimilan**
Continuation of https://github.com/JuliaStats/DataFramesMeta.jl/pull/61, whose parent repository has been removed.

### CODE REVIEW

**Comment by bramtayl** [comment]
Hmm, looking back on this I've learned a few new things. For example, the multi-line quote blocks will introduce extraneous line number information. Also, the bug that caused issues with macrotools is gone (I think it was the kw vs = distinction), so I could add back in more macrotools.

**Comment by bramtayl** [comment]
However, I'm hard at work on LazyQuery, which when complete should have the same functionality with substantially simpler syntax and more flexibility with dispatch. Any help would be appreciated.

**Comment by nalimilan** [comment]
I just wanted to apply the minimal fixes to get the package working on Julia 0.6. I'd rather leave further improvements for later, especially given that I'm not very good at macro tricks.

**Comment by ararslan** [comment]
I'd also prefer we not add a dependency on MacroTools here

**Comment by nalimilan** [comment]
(Though I must say I'm having quite a hard time fixing the failures, so without help I probably won't succeed...)

**Comment by nalimilan** [comment]
Merging since tests still pass on 0.4 and 0.5.

**Comment by bramtayl** [comment]
It looks like the 0.6 issues are being caused by the current module deprecation. Here is some code from LazyContext that might help:

```
if VERSION < v"0.7.0-DEV.484" # Julia PR #22064
    my_macroexpand(m::Module, ex) = eval(m, :(macroexpand($(Expr(:quote, ex)))))
    __module__ = :( current_module() )
    export @__MODULE__
    """
        @__MODULE__

    Return the current module, for compatibility with older versions of
    Julia.
    """
    macro __MODULE__()
        esc(__module__)
    end
else
    my_macroexpand = macroexpand
end
```
If you want I can put in a PR.

**Comment by nalimilan** [comment]
It would be great if you could make a PR. Fixing things that are probably trivial to somebody familiar with macros like you would probably take me hours if not days to fix.

**Comment by bramtayl** [comment]
Aw shucks!

**Comment by bramtayl** [comment]
Ok I'll take a look this evening

**Pull request merged**
