### PR TITLE
Remove type piracy on Base.select(::Associative)

### PR DESCRIPTION
**Pull request by tkelman**
is this needed to make things work here? If so, can that be refactored?

### CODE REVIEW

**Comment by tkelman** [comment]
Anyone know what this is used for here? Would it work to use a package-local DataFramesMeta.select without importing it? Pretty fishy to be relying on behavior of Associative that Base doesn't define.

**Comment by nalimilan** [comment]
I think the type piracy is due to a more fundamental function piracy: `select` is used in the SQL sense in this package, which has nothing to do with `Base.select`. That's not a big deal for data frames, but it's more annoying for `Dict`, and yet the package supports operations on both types.

A solution would be to unexport all functions like `select`, since IIRC they are mostly intended to be used via macros like `@select` or inside a `@linq` block (which could automatically add the required prefix).

**Comment by nalimilan** [comment]
Great, I wouldn't have expected this to be so easy! But maybe we should apply this change more systematically? It would feel weird to be unable to access `select` directly, but that it would work for other functions.

**Comment by tkelman** [comment]
There actually doesn't seem to be a whole lot of method extension here - other than these `select`s, https://github.com/JuliaStats/DataFramesMeta.jl/search?utf8=%E2%9C%93&q=+Base&type= shows `names`, `hcat`, `values` in a test (which is maybe a bit dubious too). Since the results shown per file are limited, we can see there are also normal things like `getindex`, `size`, `start`, `next`, `done`, `length`, `map`, all of which look fine. And I don't see any `import` or `importall` in this package.

**Comment by nalimilan** [comment]
I just meant that `where`, `orderby`, and `transform` should be unexported too.

**Comment by tkelman** [comment]
Like that?

**Comment by tkelman** [comment]
May be worth opening an issue in Base and think about moving select into the Sort module?

**Comment by tshort** [comment]
I had intended on exposing the functions in the API, but I'm good with removing that and limiting the API to the macro use. I'm also fine with removing support for Dicts.

**Comment by nalimilan** [comment]
Thanks for commenting @tshort. Let's unexport these functions for now, and hopefully we can rename `Base.select` so that it's available for packages in 1.0.

**Pull request merged**
