### PR TITLE
removed 0.4 deprecation wanrings

### PR DESCRIPTION
**Pull request by merl-dev**

### CODE REVIEW

**Comment by tshort** [comment]
Does this still work with Julia v0.3?

**Comment by alyst** [comment]
Only when wrapped in `@compat()`

**Comment by ViralBShah** [comment]
How about we do 0.4 changes, and tag new releases for Julia 0.4?

**Comment by tshort** [comment]
Good plan, Viral.

**Comment by tkelman** [comment]
Adding `@compat` would be pretty harmless, this doesn't seem like a very good reason to drop 0.3 support just yet.

Should really turn on travis here.

**Comment by ViralBShah** [comment]
Yes, we can add `@compat` here, but I figured there was no problem making this work on master at least and merging the PR.

**Comment by alyst** [comment]
BTW, are there some core-devs-approved guidelines/recommendations for dropping 0.3 support in the packages?

**Comment by tkelman** [comment]
See the readme on METADATA.jl. If you drop 0.3 support, be sure to change your REQUIRE file to say `julia 0.4` and increment at least the minor package version via `Pkg.tag("Foo", :minor)`

**Comment by alyst** [comment]
@tkelman thanks!

**Pull request merged**
