### PR TITLE
Add `@byrow`

### PR DESCRIPTION
**Pull request by davidagold**
This PR includes `@byrow`, a macro for working with DataFrame objects row-by-row. Includes `/src/byrow.jl`, an addition to `test/dataframes.jl` and an addition to `README.md`.

### CODE REVIEW

**Comment by davidagold** [comment]
All right, I think it's ready to go.

**Comment by tshort** [comment]
Thanks, @davidagold! Can you squash the commits? I not, no big deal.

**Comment by davidagold** [comment]
@tshort Here you go!

**Comment by tshort** [comment]
Thanks for the contribution @davidagold!

**Comment by davidagold** [comment]
My pleasure.

**Comment by bramtayl** [comment]
As long as we're adding rowwise data building, it would be pretty cool to add other SAS like functions (set, lag, output, etc)

**Comment by davidagold** [comment]
@bramtayl I'm not familiar with SAS, but if you describe a particular feature you'd like to see implemented I'm happy to take a whack at it.

**Pull request merged**
