### PR TITLE
DataFrames 0.11 support

### PR DESCRIPTION
**Pull request by nalimilan**
Also drop support for Julia 0.5 and NullableArrays.

### CODE REVIEW

**Comment by nalimilan** [comment]
I don't understand why tests fail, as they pass locally on 0.6. Ideas?

**Comment by ararslan** [comment]
Wow, excellent failure message: `ERROR: LoadError: "Tests failed"`. A+

**Comment by tshort** [comment]
I like! I like! I love the way DataFrames now supports more vector types, including `Vector`.

The crappy error message for failed tests is my fault. I can't imagine why I did it that way.

I'll see if I can reproduce test failures locally (but no guarantees as all I've got is a windows laptop on travel).

**Comment by tshort** [comment]
I think `test/REQUIRE` needs `DataArrays` added.

**Comment by nalimilan** [comment]
Cool, thanks! Tests pass on 0.6 now.

The best solution will be to move to testsets eventually.

**Pull request merged**
